# Generated by Django 5.0 on 2023-12-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_alter_user_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
